# Generated by Django 2.1.7 on 2019-02-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
    ]
