# Generated by Django 2.1.7 on 2019-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_balance', '0002_remove_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
